#!/bin/sh

# コミットメッセージ入力前に、ブランチ名から Issue 番号を抽出して置換する
COMMIT_MSG_FILE=$1
MESSAGE=$(cat "$COMMIT_MSG_FILE")

ISSUE_NUMBER=$(git rev-parse --abbrev-ref HEAD | grep -Eo "^(feature|bugfix|release)/[0-9]+"" | grep -Eo "[0-9]+")
if [ -z "$ISSUE_NUMBER" ]; then
  read -p "Issue 番号がブランチ名にないので置換できませんが、続行しますか？ (y/N): " YM < /dev/tty
  case "$YM" in
    [yY]*) sed -i "s/(#Issue)//" $COMMIT_MSG_FILE ;;
    *) echo "abort." ; exit 1 ;;
  esac
fi

sed -i "s/(#Issue)/(#$ISSUE_NUMBER)/" $COMMIT_MSG_FILE
