# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export LANG=ja_JP.UTF-8

# Command Completions
if type volta &>/dev/null
then
  for COMPLETION in "${HOME}/bash_completion/"*
  do
    [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
  done
fi

## Terraform
### USERの部分は置換すること
complete -C C:/Users/{USER}/development/library/terraform/terraform.exe terraform.exe
