command_timeout = 1500

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) >> "
show_always = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "bold orange"

[memory_usage]
disabled = false
threshold = -1
format = "via $symbol [${ram_pct}( | ${swap_pct})]($style) "
style = "bold dimmed green"
